approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

httpRetry: 10

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

preferReuse: true

yarnPath: .yarn/releases/yarn-4.14.1.cjs
