// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./es-git.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-android-arm64')
        const bindingPackageVersion = require('es-git-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./es-git.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-android-arm-eabi')
        const bindingPackageVersion = require('es-git-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./es-git.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-win32-x64-gnu')
        const bindingPackageVersion = require('es-git-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./es-git.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-win32-x64-msvc')
        const bindingPackageVersion = require('es-git-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./es-git.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-win32-ia32-msvc')
        const bindingPackageVersion = require('es-git-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./es-git.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-win32-arm64-msvc')
        const bindingPackageVersion = require('es-git-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./es-git.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('es-git-darwin-universal')
      const bindingPackageVersion = require('es-git-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./es-git.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-darwin-x64')
        const bindingPackageVersion = require('es-git-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./es-git.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-darwin-arm64')
        const bindingPackageVersion = require('es-git-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./es-git.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-freebsd-x64')
        const bindingPackageVersion = require('es-git-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./es-git.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-freebsd-arm64')
        const bindingPackageVersion = require('es-git-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./es-git.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-x64-musl')
          const bindingPackageVersion = require('es-git-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./es-git.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-x64-gnu')
          const bindingPackageVersion = require('es-git-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./es-git.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-arm64-musl')
          const bindingPackageVersion = require('es-git-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./es-git.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-arm64-gnu')
          const bindingPackageVersion = require('es-git-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./es-git.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-arm-musleabihf')
          const bindingPackageVersion = require('es-git-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./es-git.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-arm-gnueabihf')
          const bindingPackageVersion = require('es-git-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./es-git.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-loong64-musl')
          const bindingPackageVersion = require('es-git-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./es-git.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-loong64-gnu')
          const bindingPackageVersion = require('es-git-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./es-git.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-riscv64-musl')
          const bindingPackageVersion = require('es-git-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./es-git.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('es-git-linux-riscv64-gnu')
          const bindingPackageVersion = require('es-git-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./es-git.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-linux-ppc64-gnu')
        const bindingPackageVersion = require('es-git-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./es-git.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-linux-s390x-gnu')
        const bindingPackageVersion = require('es-git-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./es-git.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-openharmony-arm64')
        const bindingPackageVersion = require('es-git-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./es-git.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-openharmony-x64')
        const bindingPackageVersion = require('es-git-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./es-git.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('es-git-openharmony-arm')
        const bindingPackageVersion = require('es-git-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.5.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./es-git.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('es-git-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AnnotatedCommit = nativeBinding.AnnotatedCommit
module.exports.Blame = nativeBinding.Blame
module.exports.BlameHunks = nativeBinding.BlameHunks
module.exports.BlameHunksByLine = nativeBinding.BlameHunksByLine
module.exports.Blob = nativeBinding.Blob
module.exports.Branch = nativeBinding.Branch
module.exports.Branches = nativeBinding.Branches
module.exports.Commit = nativeBinding.Commit
module.exports.Config = nativeBinding.Config
module.exports.ConfigEntries = nativeBinding.ConfigEntries
module.exports.Deltas = nativeBinding.Deltas
module.exports.Describe = nativeBinding.Describe
module.exports.Diff = nativeBinding.Diff
module.exports.DiffDelta = nativeBinding.DiffDelta
module.exports.DiffFile = nativeBinding.DiffFile
module.exports.DiffStats = nativeBinding.DiffStats
module.exports.GitObject = nativeBinding.GitObject
module.exports.Index = nativeBinding.Index
module.exports.IndexEntries = nativeBinding.IndexEntries
module.exports.Mailmap = nativeBinding.Mailmap
module.exports.Note = nativeBinding.Note
module.exports.Notes = nativeBinding.Notes
module.exports.Rebase = nativeBinding.Rebase
module.exports.Reference = nativeBinding.Reference
module.exports.Reflog = nativeBinding.Reflog
module.exports.ReflogEntry = nativeBinding.ReflogEntry
module.exports.ReflogIter = nativeBinding.ReflogIter
module.exports.Remote = nativeBinding.Remote
module.exports.Repository = nativeBinding.Repository
module.exports.Revwalk = nativeBinding.Revwalk
module.exports.StashEntry = nativeBinding.StashEntry
module.exports.StashList = nativeBinding.StashList
module.exports.StashListIter = nativeBinding.StashListIter
module.exports.StatusEntry = nativeBinding.StatusEntry
module.exports.Statuses = nativeBinding.Statuses
module.exports.StatusesIter = nativeBinding.StatusesIter
module.exports.Submodule = nativeBinding.Submodule
module.exports.Tag = nativeBinding.Tag
module.exports.Tree = nativeBinding.Tree
module.exports.TreeEntry = nativeBinding.TreeEntry
module.exports.TreeIter = nativeBinding.TreeIter
module.exports.Worktree = nativeBinding.Worktree
module.exports.ApplyLocation = nativeBinding.ApplyLocation
module.exports.AutotagOption = nativeBinding.AutotagOption
module.exports.BranchType = nativeBinding.BranchType
module.exports.cloneRepository = nativeBinding.cloneRepository
module.exports.ConfigLevel = nativeBinding.ConfigLevel
module.exports.createMailmapFromBuffer = nativeBinding.createMailmapFromBuffer
module.exports.createSignature = nativeBinding.createSignature
module.exports.CredentialType = nativeBinding.CredentialType
module.exports.DeltaType = nativeBinding.DeltaType
module.exports.DiffFlags = nativeBinding.DiffFlags
module.exports.diffFlagsContains = nativeBinding.diffFlagsContains
module.exports.DiffFormat = nativeBinding.DiffFormat
module.exports.Direction = nativeBinding.Direction
module.exports.discoverRepository = nativeBinding.discoverRepository
module.exports.FetchPrune = nativeBinding.FetchPrune
module.exports.FileFavor = nativeBinding.FileFavor
module.exports.FileMode = nativeBinding.FileMode
module.exports.findGlobalConfigPath = nativeBinding.findGlobalConfigPath
module.exports.findSystemConfigPath = nativeBinding.findSystemConfigPath
module.exports.findXdgConfigPath = nativeBinding.findXdgConfigPath
module.exports.hashFileOid = nativeBinding.hashFileOid
module.exports.hashObjectOid = nativeBinding.hashObjectOid
module.exports.IndexStage = nativeBinding.IndexStage
module.exports.initRepository = nativeBinding.initRepository
module.exports.isValidBranchName = nativeBinding.isValidBranchName
module.exports.isValidOid = nativeBinding.isValidOid
module.exports.isValidReferenceName = nativeBinding.isValidReferenceName
module.exports.isValidTagName = nativeBinding.isValidTagName
module.exports.isZeroOid = nativeBinding.isZeroOid
module.exports.normalizeReferenceName = nativeBinding.normalizeReferenceName
module.exports.ObjectType = nativeBinding.ObjectType
module.exports.openConfig = nativeBinding.openConfig
module.exports.openDefaultConfig = nativeBinding.openDefaultConfig
module.exports.openRepository = nativeBinding.openRepository
module.exports.parseConfigBool = nativeBinding.parseConfigBool
module.exports.parseConfigI32 = nativeBinding.parseConfigI32
module.exports.parseConfigI64 = nativeBinding.parseConfigI64
module.exports.RebaseOperationType = nativeBinding.RebaseOperationType
module.exports.ReferenceFormat = nativeBinding.ReferenceFormat
module.exports.ReferenceType = nativeBinding.ReferenceType
module.exports.RemoteRedirect = nativeBinding.RemoteRedirect
module.exports.RepositoryInitMode = nativeBinding.RepositoryInitMode
module.exports.RepositoryState = nativeBinding.RepositoryState
module.exports.RevparseMode = nativeBinding.RevparseMode
module.exports.revparseModeContains = nativeBinding.revparseModeContains
module.exports.RevwalkSort = nativeBinding.RevwalkSort
module.exports.StatusShow = nativeBinding.StatusShow
module.exports.SubmoduleIgnore = nativeBinding.SubmoduleIgnore
module.exports.SubmoduleStatus = nativeBinding.SubmoduleStatus
module.exports.submoduleStatusContains = nativeBinding.submoduleStatusContains
module.exports.SubmoduleUpdate = nativeBinding.SubmoduleUpdate
module.exports.traceClear = nativeBinding.traceClear
module.exports.TraceLevel = nativeBinding.TraceLevel
module.exports.traceSet = nativeBinding.traceSet
module.exports.TreeWalkMode = nativeBinding.TreeWalkMode
module.exports.zeroOid = nativeBinding.zeroOid
