name: Release
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
env:
  DEBUG: napi:*
  APP_NAME: es-git
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-15-intel
            target: x86_64-apple-darwin
            build: yarn build --target x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
            build: yarn build --target aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: yarn build --target x86_64-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: yarn build --target aarch64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: yarn build --target x86_64-unknown-linux-gnu --use-napi-cross
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: yarn build --target x86_64-unknown-linux-musl -x
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: yarn build --target aarch64-unknown-linux-gnu --use-napi-cross
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: yarn build --target aarch64-unknown-linux-musl -x
          - host: ubuntu-latest
            target: aarch64-linux-android
            build: yarn build --target aarch64-linux-android
          - host: ubuntu-latest
            target: armv7-linux-androideabi
            build: yarn build --target armv7-linux-androideabi
    name: build (${{ matrix.settings.target }})
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: yarn
      - name: Install rust
        uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
        with:
          toolchain: "1.91.0"
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # 2.2.1
        if: ${{ contains(matrix.settings.target, 'musl') }}
        with:
          version: 0.14.1
      - name: Install cargo-zigbuild
        uses: taiki-e/install-action@288875dd3d64326724fa6d9593062d9f8ba0b131 # 2.67.30
        if: ${{ contains(matrix.settings.target, 'musl') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      deployments: write
    needs:
      - build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: yarn
      - name: Update npm
        run: npm install -g npm@11.5.1
      - name: Install dependencies
        run: yarn install
      - name: Download all artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: release-artifacts
      - name: Prepare next release
        if: github.ref_type == 'branch'
        run: node --no-warnings=ExperimentalWarning --experimental-strip-types ./.scripts/prepare-next-release.ts ${{ github.run_number }} ${{ github.sha }}
      - name: Create npm dirs
        run: yarn napi create-npm-dirs
      - name: Move artifacts
        run: yarn napi artifacts -d release-artifacts
      - name: List packages
        run: ls -R ./npm
        shell: bash
      - id: extract-changelog
        uses: dahlia/submark@5a5ff0a58382fb812616a5801402f5aef00f90ce
        with:
          input-file: CHANGELOG.md
          heading-level: 2
          heading-title-text: version ${{ github.ref_name }}
          ignore-case: true
          omit-heading: true
      - run: 'cat ${{ steps.extract-changelog.outputs.output-file }}'
      - name: Release
        id: gh-release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: github.ref_type == 'tag'
        with:
          body_path: ${{ steps.extract-changelog.outputs.output-file }}
          repository: toss/es-git
          generate_release_notes: false
          token: ${{ github.token }}
      - name: Publish
        id: publish
        run: |
          set -ex
          if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
            yarn napi prepublish -t npm --gh-release-id ${{ steps.gh-release.outputs.id }}
            npm publish --provenance --access public
          elif [[ "$GITHUB_REF_TYPE" = "branch" ]]; then
            npm config set tag next
            yarn napi prepublish -t npm --no-gh-release
            npm publish --provenance --access public --tag next
          else
            echo "Skip publish"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
  publish-docs:
    runs-on: ubuntu-latest
    needs:
      - release
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Pull Vercel Environment Information
        run: yarn dlx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: yarn dlx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: yarn dlx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
